---
Name: userforms-tidying
After: '#userformsconfig'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'bigfork/silverstripe-userforms-tidying:client/dist/styles/bundle.css'
DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - Bigfork\SilverstripeUserFormsTidying\UserFormCMSFieldsExtension
    - Bigfork\SilverstripeUserFormsTidying\ElementFormExtension
SilverStripe\UserForms\Model\EditableFormField:
  extensions:
    - Bigfork\SilverstripeUserFormsTidying\EditableFormFieldExtension
SilverStripe\UserForms\Model\EditableFormField\EditableCountryDropdownField:
  hidden: true
SilverStripe\UserForms\Model\EditableFormField\EditableFileField:
  hidden: true
SilverStripe\UserForms\Model\EditableFormField\EditableMemberListField:
  hidden: true
SilverStripe\UserForms\Model\EditableFormField\EditableNumericField:
  hidden: true
SilverStripe\UserForms\Model\UserDefinedForm:
  upgrade_on_build: false
